# Generated by Django 4.0.4 on 2022-05-23 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weight_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weighttracker',
            name='birthday',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='weighttracker',
            name='current_weight',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='weighttracker',
            name='height',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='weighttracker',
            name='weight_goal',
            field=models.IntegerField(),
        ),
    ]
