# Generated by Django 4.0.4 on 2022-05-27 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weight_tracker', '0002_alter_weighttracker_birthday_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weighttracker',
            name='date',
            field=models.DateField(default=2020),
            preserve_default=False,
        ),
    ]
