# Generated by Django 4.0.4 on 2022-05-27 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weight_tracker', '0003_weighttracker_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weighttracker',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
